[project]
name = 'robblock_contract'
description = ''
authors = []
telemetry = true
cache_dir = '.\.cache'
requirements = []
[contracts.donation_tracker]
path = 'contracts/donation_tracker.clar'
clarity_version = 2
epoch = 2.5

[contracts.impact_reporting]
path = 'contracts/impact_reporting.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
